# This file is part of the Shared Kernel library.
#
# Copyright (c) 2016-present LIN3S <info@lin3s.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

sudo: false

language: php

php:
    - 7.1

before_script:
    - composer self-update
    - composer install --prefer-source

script:
    - vendor/bin/phpspec run -fpretty

    - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run
    - vendor/bin/php-cs-fixer fix --config=.phpspec_cs --verbose --diff --dry-run

cache:
    directories:
        - $COMPOSER_CACHE_DIR
        - $HOME/.php-cs-fixer
